In [1]:
import numpy as np

#  #zeros, # ones, # eye, #diag, # randint, # rand, # randn

# 1-d array define kiya hai idher

In [11]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

# lets define the tuple:

In [12]:
arr0 = np.zeros((2,3))
arr0

array([[0., 0., 0.],
       [0., 0., 0.]])

# this above ouput shown is the tuple of 2x3(order)

In [13]:
arr1 = np.ones((2,3))
arr1

array([[1., 1., 1.],
       [1., 1., 1.]])

# eye function begin:-
# It creates the 2d matrix whose diagonal elements will be 1 and rest will be 0

In [14]:
arr2 = np.eye(4)
arr2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
arr34 = np.eye(3,4)
arr34

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# diag function begins :-
### --> It creates matrix with diagonal values as passed in it.
### --> for eg. np.diag([1,2,3,4]) will creat the diagonal with this numbers and rest will bw zero

In [16]:
arr3 = np.diag([1,2,3,4])
arr3

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

# In order to know the diagonal elements of any matrix then :
# np.diag(matrix)  this will give the diagonal elements of the matrix

In [17]:
diag_elements = np.diag(arr3)
diag_elements

array([1, 2, 3, 4])

# Generate the random numbers from one interval to another :
### As shown below: (first_interval, last_interval, no_of_randomNumbers_needed)

In [18]:
rand_arr = np.random.randint(1, 15, 5)
rand_arr

array([ 1, 14,  7,  3, 13])

In [20]:
rand_arr_from_0to1 = np.random.rand(10)
rand_arr_from_0to1

array([0.09356948, 0.3258859 , 0.40818087, 0.38762966, 0.1686861 ,
       0.44968462, 0.61364467, 0.12524368, 0.68520523, 0.45306575])

# ye jo random value generate ho rha hai vo uniform distribution se aara hai

In [21]:
randArray_matrix = np.random.rand(2,3)
randArray_matrix

array([[0.98607335, 0.01525749, 0.57914978],
       [0.42175818, 0.3419711 , 0.50344245]])

# randn() :--
### It gives random numbers jo centered hoga 0 ke(comes via Std. Normal distribution)

In [23]:
normal_distribution_randn = np.random.randn(4)
normal_distribution_randn

array([-0.24081198,  0.19291466,  1.01416649, -0.07040233])

In [24]:
randArray_matrix1 = np.random.randn(2,3)
randArray_matrix1

array([[-1.12487634,  0.76317691,  0.12451742],
       [-1.35365266,  0.47043897, -1.37730374]])

In [31]:
random_40_randn = np.random.randn(1500)
random_40_randn

array([-0.13847472,  0.38559038,  0.2868006 , ..., -0.022143  ,
       -1.28014122,  0.96505628])

In [32]:
np.mean(random_40_randn)

0.04752019583896318