# 1. Reshaping of the data

In [8]:
import numpy as np

In [15]:
arr = np.random.randint(1, 100, 20)
arr = arr.reshape(2,10)

In [16]:
arr

array([[15, 47, 91, 59, 66,  2, 97, 30, 28, 62],
       [34, 97, 92, 64, 48, 89, 53, 98, 88, 92]])

In [17]:
arr.ndim

2

#### ouput as 1 shows that its a 1d array

In [18]:
arr.shape

(2, 10)

# reshape ke ander wali value ka product 50 aa rha hai, aisa har case me hona chahiye. for eg, 10 x 5 = 50

In [19]:
arr1 = np.random.randint(1, 100, 50)
arr1 = arr1.reshape(10, 5)

In [20]:
arr1

array([[69, 42, 97, 60,  6],
       [59, 27, 59, 17, 38],
       [40, 22, 19, 90, 29],
       [12, 72, 17, 26,  3],
       [72,  7, 34, 97, 62],
       [73, 57, 86, 17, 38],
       [31, 99, 76, 69, 12],
       [51, 28, 71, 66, 89],
       [43, 29, 33, 58, 31],
       [99, 46, 71, 75, 84]])

In [23]:
arr2 = np.random.randint(1, 100, 50)
arr2 = arr1.reshape(2, 5, 5)

In [24]:
arr2

array([[[69, 42, 97, 60,  6],
        [59, 27, 59, 17, 38],
        [40, 22, 19, 90, 29],
        [12, 72, 17, 26,  3],
        [72,  7, 34, 97, 62]],

       [[73, 57, 86, 17, 38],
        [31, 99, 76, 69, 12],
        [51, 28, 71, 66, 89],
        [43, 29, 33, 58, 31],
        [99, 46, 71, 75, 84]]])

#  Tutorial - 8 : NumPy: -1 in reshape

In [25]:
Arr = np.arange(1, 11)

In [26]:
Arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
Arr.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# On putting -1 we got the same results... becoz python checks the product i.e here is 10, if its not coming then its automatically checkout..

In [29]:
Arr.reshape(5, -1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [30]:
Arr1 = np.arange(1, 111)

In [31]:
Arr1

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110])

In [32]:
Arr1.size

110

In [33]:
Arr1.reshape(5, -1)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22],
       [ 23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
         36,  37,  38,  39,  40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
         58,  59,  60,  61,  62,  63,  64,  65,  66],
       [ 67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
         80,  81,  82,  83,  84,  85,  86,  87,  88],
       [ 89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
        102, 103, 104, 105, 106, 107, 108, 109, 110]])

In [34]:
Arr1.reshape(-1, 5)

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110]])

# Tutorial-9 : Seed function

In [44]:
# np.random.seed(123) 
# for getting the fixed random numbers by passing the some seed value
np.random.seed(123)
Ar = np.random.randint(1, 101, 10)
Ar

array([67, 93, 99, 18, 84, 58, 87, 98, 97, 48])

In [45]:
Ar.size

10

#  here, size is not a function but its an attribute for finding size of array

In [48]:
np.random.seed(123)
Arr1_reshape = np.random.randint(1, 101, 15).reshape(3,5)
Arr1_reshape

array([[67, 93, 99, 18, 84],
       [58, 87, 98, 97, 48],
       [74, 33, 47, 97, 26]])