# NumPy : Indexing And Slicing of 1-d array

In [ ]:
import numpy as np

In [5]:
arr = np.array([5, 10, 15, 20, 25])

In [6]:
arr

array([ 5, 10, 15, 20, 25])

In [7]:
arr[0]

5

In [8]:
arr[1]

10

In [9]:
arr[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [10]:
arr

array([ 5, 10, 15, 20, 25])

In [11]:
arr[-1]

25

In [12]:
arr[-4]

10

# Slicing:-

In [13]:
arr[0 : 2]

array([ 5, 10])

In [14]:
arr[1 : 3]

array([10, 15])

In [15]:
arr[1 : ]

array([10, 15, 20, 25])

In [16]:
arr[-3 : ]

array([15, 20, 25])

In [17]:
arr[ : ]

array([ 5, 10, 15, 20, 25])

In [18]:
arr[1 : 4]

array([10, 15, 20])

In [19]:
arr[1 : 4 : 1]

array([10, 15, 20])

In [20]:
arr[1 : 4 : 2]

array([10, 20])

# reverse the array

In [21]:
arr[ : : -1]

array([25, 20, 15, 10,  5])