# 1. Create a 2-D array:

In [4]:
import numpy as np

In [5]:
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [6]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

# 2. Indexing using double bracket notation:

In [7]:
matrix[0][1]

10

In [8]:
matrix[1][1]

25

# 3. Indexing using single bracket notation(Recommended)

In [9]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [10]:
matrix[0,1]

10

In [11]:
matrix[1, 1]

25

# 4. Slicing using single bracket notation

In [12]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [13]:
# [[ 5 ,10],
#  [20, 25]]

In [14]:
matrix[ : 2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [15]:
matrix[ : 2, : 2]  # matrix[row kha se start hoga : row kha tak end hoga, col. kha se start hoga : col. kha tak end hoga]

array([[ 5, 10],
       [20, 25]])

In [16]:
# [[25, 30],
#  [40, 45]]

In [17]:
matrix[1 : , 1 : ]

array([[25, 30],
       [40, 45]])

In [18]:
np.random.seed(123)
matrix2 = np.random.randint(1, 101, 25).reshape(5,5)
matrix2

array([[67, 93, 99, 18, 84],
       [58, 87, 98, 97, 48],
       [74, 33, 47, 97, 26],
       [84, 79, 37, 97, 81],
       [69, 50, 56, 68,  3]])

In [19]:
# 87, 98, 97
# 33, 47, 97
# 79, 37, 97

In [20]:
matrix2[1 : 3, 1 : 3]

array([[87, 98],
       [33, 47]])

In [21]:
matrix2[1 : 4, 1 : 4]

array([[87, 98, 97],
       [33, 47, 97],
       [79, 37, 97]])

In [23]:
matrix2[2 : ,2 : ]

array([[47, 97, 26],
       [37, 97, 81],
       [56, 68,  3]])

# Tut - 12 begins: Numpy : View Vs Copy

In [50]:
arr = np.array([5, 10, 15, 20, 25, 30])

### Here, slice_arr has not copied the array from 2 to 4 i.e new memory has not formed rather actual location where these were stored in the arr has has been viewed here in the slice array. 

In [51]:
slice_arr = arr[2:5]

# to make a copy we can use it as...

In [52]:
slice_arr

array([15, 20, 25])

In [53]:
slice_arr[:] = 0

In [54]:
slice_arr

array([0, 0, 0])

In [56]:
arr

array([ 5, 10,  0,  0,  0, 30])

In [57]:
arr1 = np.array([5,10,15,20,25,30])

In [58]:
sliced_arr1 = arr1[2:5].copy()

In [59]:
sliced_arr1

array([15, 20, 25])

In [60]:
sliced_arr[:] = 0

In [61]:
sliced_arr

array([0, 0, 0])

In [62]:
arr1

array([ 5, 10, 15, 20, 25, 30])

### Now, we can see that arr now has not got tempered...

# Tutorial - 13 begins.... : NumPy : Conditional Selection

In [65]:
arr2 = np.arange(1, 11)

In [66]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
arr2 > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [68]:
mask = arr2 > 5

In [69]:
mask

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [70]:
arr2[mask]

array([ 6,  7,  8,  9, 10])

In [71]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
arr2[arr2 < 4]

array([1, 2, 3])

In [74]:
arr2[arr2 % 2 == 0]

array([ 2,  4,  6,  8, 10])

In [75]:
arr2[arr2 % 2 == 0] = 0

In [76]:
arr2

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])

# Tutorial - 14 begins... : Numpy: Operations on array with scaler

In [77]:
arr3 = np.array([1,2,3,4])

In [78]:
arr3 * 2

array([2, 4, 6, 8])

In [79]:
arr3 + 5

array([6, 7, 8, 9])

In [80]:
arr3 ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [81]:
# Above this operations on array with scalar can be performed with 2d array as well...

In [82]:
arr4 = np.array([1,2,3,4]).reshape(2,2)

In [83]:
arr4

array([[1, 2],
       [3, 4]])

In [84]:
arr4 ** 2

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [85]:
arr4 + 5

array([[6, 7],
       [8, 9]])

In [86]:
arr4 / 0

<ipython-input-86-10c233e0a2b0>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr4 / 0


array([[inf, inf],
       [inf, inf]])

# Tutorial - 15 begins... : NumPy : operations on two or more array

In [91]:
Arr1 = np.array([1,2,3,4])
Arr2 = np.array([5,6,7,8])
Arr3 = np.array([9,10,11,12])

In [92]:
Arr1 * Arr2

array([ 5, 12, 21, 32])

In [93]:
Arr1 / Arr2

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [95]:
Arr1 ** Arr2

array([    1,    64,  2187, 65536], dtype=int32)

In [96]:
Arr1 * Arr2 + Arr3

array([14, 22, 32, 44])

In [102]:
np.random.seed(123)
matrix_1 = np.random.randint(1,12,9).reshape(3,3)
matrix_2 = np.random.randint(5,15,9).reshape(3,3)

In [103]:
matrix_1

array([[ 3,  3,  7],
       [ 2,  4, 11],
       [10,  7,  2]])

In [104]:
matrix_2

array([[ 5,  6, 14],
       [ 5,  5, 14],
       [ 8,  9,  5]])

In [105]:
matrix_1 + matrix_2

array([[ 8,  9, 21],
       [ 7,  9, 25],
       [18, 16,  7]])

In [106]:
matrix_1.dot(matrix_2)

array([[ 86,  96, 119],
       [118, 131, 139],
       [101, 113, 248]])