In [1]:
import numpy as np

In [3]:
np.random.seed(123)
matrix = np.random.randint(1, 11, 9).reshape(3,3)

In [4]:
matrix

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [6]:
# np.sum(matrix)
# other way to do the same is matrix.sum()
matrix.sum()

39

In [7]:
np.min(matrix)

1

In [8]:
np.max(matrix)

10

In [13]:
# for row = 1 and column = 0 (need to rememeber this for using axis with a value)

In [14]:
matrix

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [15]:
np.min(matrix, axis = 1)

array([3, 2, 1])

In [16]:
np.max(matrix, axis = 0)

array([ 7,  4, 10])

In [17]:
np.sum(matrix, axis = 1)

array([13, 16, 10])

In [18]:
np.sum(matrix, axis = 0)

array([12,  9, 18])

In [19]:
np.cumsum(matrix)

array([ 3,  6, 13, 15, 19, 29, 36, 38, 39], dtype=int32)

In [20]:
# this cumsum(cummulative sum can be performed along row and column as well)

In [21]:
np.cumsum(matrix, axis = 0)

array([[ 3,  3,  7],
       [ 5,  7, 17],
       [12,  9, 18]], dtype=int32)

In [22]:
np.prod(matrix, axis = 1)

array([63, 80, 14])

# Tutorial - 18 : NumPy : shuffle and unique

In [24]:
np.random.seed(123)
arr4 = np.random.randint(1, 15, 15)

In [25]:
arr4

array([14,  3, 13,  3,  7,  2,  4, 11, 12, 10,  7,  2,  1,  2, 10])

In [26]:
np.random.shuffle(arr4)

In [27]:
arr4

array([ 4,  2, 11, 12, 13,  2,  3,  7,  1,  2,  7,  3, 10, 10, 14])

In [29]:
np.unique(arr4)

array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14])

In [30]:
np.unique(arr4).size

10

In [32]:
np.unique(arr4, return_index = True, return_counts = True)

(array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14]),
 array([ 8,  1,  6,  0,  7, 12,  2,  3,  4, 14], dtype=int64),
 array([1, 3, 2, 1, 2, 2, 1, 1, 1, 1], dtype=int64))

In [33]:
# Above there are 3 arrays as output we got here :-
# (1) first array is the array of all unique elements.
# (2) array of all index of elements which are unique
# (3) freq. of all unique elements.

# Tutorial - 19 : NumPy : Horizontal and Vertical Stacking

In [34]:
np.random.seed(123)
matrix1 = np.random.randint(1, 20, 9).reshape(3, 3)
matrix2 = np.random.randint(20, 40, 9).reshape(3, 3)

In [35]:
matrix1

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18]])

In [36]:
matrix2

array([[35, 29, 20],
       [34, 20, 35],
       [39, 34, 24]])

In [37]:
# Horizontal Stacking means concatenating matirx horizontally

In [38]:
np.hstack((matrix1, matrix2))

array([[14,  3,  3, 35, 29, 20],
       [ 7, 18, 11, 34, 20, 35],
       [ 2,  1, 18, 39, 34, 24]])

In [40]:
# Vertical Stacking : as shown below.

In [41]:
np.vstack((matrix1, matrix2))

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18],
       [35, 29, 20],
       [34, 20, 35],
       [39, 34, 24]])

In [42]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])

In [43]:
np.hstack((arr_1, arr_2))

array([1, 2, 3, 4, 5, 6])

In [44]:
np.vstack((arr_1, arr_2))

array([[1, 2, 3],
       [4, 5, 6]])