# Import numpy library

In [1]:
import numpy as np

# Create an Array using array function

In [3]:
arr = [1,2,3,4,5,6]
np.array(arr)
arr

[1, 2, 3, 4, 5, 6]

# Create an Array containing numbers from 20 to 40

In [16]:
arr1 = np.random.randint(20, 41, 10) # this will give random numbers not the range of numbers !!! (mind it !!)
arr1

array([25, 21, 37, 40, 39, 26, 33, 29, 36, 31])

In [17]:
# Other way to do the same:--
arr_arange = np.arange(20, 41)
arr_arange

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40])

# Create an array which contain 10 elements and every element is 5

In [5]:
arr2 = np.random.randint(5, 6, 10)
arr2

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [20]:
# Other way to do the same :--
fives = np.ones(10)
fives*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

# create a 1-d array and then convert it into 3-d array

In [21]:
oneD_to_3d_array = np.random.randint(1, 21, 24).reshape(4, 2, 3)  # mind it !! : 24 = 4 * 2 * 3
oneD_to_3d_array

array([[[ 8,  9,  4],
        [14,  6, 12]],

       [[14,  5, 18],
        [ 9,  1, 17]],

       [[11,  5, 12],
        [16, 11, 14]],

       [[15,  4, 17],
        [10,  6, 10]]])

# Create 2-d array which contains random 25 numbers between 0 and 1

In [10]:
array_2d = np.random.randint(0, 2, 25).reshape(5, 5)
array_2d

array([[1, 0, 1, 1, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 0, 1]])

In [23]:
# Here, question is asking to find random number b/w 0 to 1:
random_01 = np.random.rand(25).reshape(5, 5)
random_01

array([[0.93293021, 0.19550825, 0.4258276 , 0.04834257, 0.53500053],
       [0.10323527, 0.67167862, 0.04698927, 0.9410221 , 0.03561886],
       [0.60951815, 0.85293116, 0.18446989, 0.45624197, 0.98906781],
       [0.68678619, 0.05790827, 0.90305438, 0.253705  , 0.27447314],
       [0.58577715, 0.16431577, 0.36962507, 0.254459  , 0.70548486]])

# create array containing 20 random integer then replace every even number with -1

In [35]:
np.random.seed(123)
arr_replaceEven = np.random.randint(1, 101,100)
arr_replaceEven

array([ 67,  93,  99,  18,  84,  58,  87,  98,  97,  48,  74,  33,  47,
        97,  26,  84,  79,  37,  97,  81,  69,  50,  56,  68,   3,  85,
        40,  67,  85,  48,  62,  49,   8, 100,  93,  53,  98,  86,  95,
        28,  35,  98,  77,  41,   4,  70,  65,  76,  35,  59,  11,  23,
        78,  19,  16,  28,  31,  53,  71,  27,  81,   7,  15,  76,  55,
        72,   2,  44,  59,  56,  26,  51,  85,  57,  50,  13,  19,  82,
         2,  52,  45,  49,  57,  92,  50,  87,   4,  68,  12,  22,  90,
        99,   4,  12,   4,  95,   7,  10,  88,  15])

In [36]:
arr_replaceEven[arr_replaceEven % 2 == 0]

array([ 18,  84,  58,  98,  48,  74,  26,  84,  50,  56,  68,  40,  48,
        62,   8, 100,  98,  86,  28,  98,   4,  70,  76,  78,  16,  28,
        76,  72,   2,  44,  56,  26,  50,  82,   2,  52,  92,  50,   4,
        68,  12,  22,  90,   4,  12,   4,  10,  88])

In [37]:
arr_replaceEven[arr_replaceEven % 2 == 0] = -1
arr_replaceEven

array([67, 93, 99, -1, -1, -1, 87, -1, 97, -1, -1, 33, 47, 97, -1, -1, 79,
       37, 97, 81, 69, -1, -1, -1,  3, 85, -1, 67, 85, -1, -1, 49, -1, -1,
       93, 53, -1, -1, 95, -1, 35, -1, 77, 41, -1, -1, 65, -1, 35, 59, 11,
       23, -1, 19, -1, -1, 31, 53, 71, 27, 81,  7, 15, -1, 55, -1, -1, -1,
       59, -1, -1, 51, 85, 57, -1, 13, 19, -1, -1, -1, 45, 49, 57, -1, -1,
       87, -1, -1, -1, -1, -1, 99, -1, -1, -1, 95,  7, -1, -1, 15])

# You have a matrix
[[5 , 10, 15, 20, 25], [30, 35, 40, 45, 50], [55, 60, 65, 70, 75], [80, 85, 90, 95, 100]]

Extract [30,35,40] [55, 60, 65]

In [42]:
arr_1 = [[5 , 10, 15, 20, 25], [30, 35, 40, 45, 50], [55, 60, 65, 70, 75], [80, 85, 90, 95, 100]]
arr_1 = np.array(arr_1)
arr_1

array([[  5,  10,  15,  20,  25],
       [ 30,  35,  40,  45,  50],
       [ 55,  60,  65,  70,  75],
       [ 80,  85,  90,  95, 100]])

In [43]:
arr_1[1 : 3, : 3]

array([[30, 35, 40],
       [55, 60, 65]])

# Concatenate two 1-d array

In [44]:
A1 = np.array([1, 2, 3, 4, 5])
A2 = np.array([6, 7, 8, 9, 10])

In [45]:
A1

array([1, 2, 3, 4, 5])

In [46]:
A2

array([ 6,  7,  8,  9, 10])

In [49]:
np.hstack((A1, A2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
np.vstack((A1, A2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# Stack 2-d matrix horizontally and vertically

In [54]:
np.random.seed(123)
matrix_1d = np.random.randint(1, 11, 25).reshape(5, 5)
matrix_2d = np.random.randint(10, 21, 25).reshape(5, 5)

In [55]:
matrix_1d

array([[ 3,  3,  7,  2,  4],
       [10,  7,  2,  1,  2],
       [10,  1,  1, 10,  4],
       [ 5,  1,  1,  5,  2],
       [ 8,  4,  3,  5,  8]])

In [56]:
matrix_2d

array([[12, 14, 18, 10, 17],
       [19, 13, 14, 16, 11],
       [15, 16, 12, 11, 18],
       [13, 20, 15, 10, 12],
       [20, 20, 16, 12, 14]])

In [57]:
np.hstack((matrix_1d, matrix_2d))

array([[ 3,  3,  7,  2,  4, 12, 14, 18, 10, 17],
       [10,  7,  2,  1,  2, 19, 13, 14, 16, 11],
       [10,  1,  1, 10,  4, 15, 16, 12, 11, 18],
       [ 5,  1,  1,  5,  2, 13, 20, 15, 10, 12],
       [ 8,  4,  3,  5,  8, 20, 20, 16, 12, 14]])

In [58]:
np.vstack((matrix_1d, matrix_2d))

array([[ 3,  3,  7,  2,  4],
       [10,  7,  2,  1,  2],
       [10,  1,  1, 10,  4],
       [ 5,  1,  1,  5,  2],
       [ 8,  4,  3,  5,  8],
       [12, 14, 18, 10, 17],
       [19, 13, 14, 16, 11],
       [15, 16, 12, 11, 18],
       [13, 20, 15, 10, 12],
       [20, 20, 16, 12, 14]])