In [1]:
import numpy as np

## Hello there kaise ho ....

### Sab badhiya hai ... tum batao yaar...

In [4]:
nums = [1, 2, 4, 5]

In [5]:
nums

[1, 2, 4, 5]

In [6]:
nums= np.array(nums)

In [7]:
nums

array([1, 2, 4, 5])

In [8]:
nums.shape

(4,)

In [9]:
nums.dtype

dtype('int32')

### tut-5 complete 

In [10]:
np.mean(nums)

3.0

In [13]:
np.sum(nums)

12

In [14]:
zeroes = np.zeros(5)

In [15]:
zeroes

array([0., 0., 0., 0., 0.])

In [17]:
z = np.zeros((4,5))

In [18]:
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
arr = np.eye(5)

In [20]:
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
arr1 = np.diag([1,2,3,4])

In [22]:
arr1

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [23]:
np.diag(arr1)

array([1, 2, 3, 4])

In [24]:
# Lets generate all random numbers b/w two numbers:
arr = np.random.randint(1, 11, 10)

In [25]:
arr

array([ 7,  1,  2, 10, 10,  2,  5,  8,  8,  2])

In [26]:
arr01 = np.random.rand(10)

In [27]:
arr01

array([0.1836706 , 0.86747442, 0.7837647 , 0.52608463, 0.13255539,
       0.39024899, 0.61327092, 0.40828396, 0.51355702, 0.92774234])

In [30]:
hello = np.random.randn(10)  # normal distribution k around random values milegi....

In [31]:
hello

array([-1.67249778, -0.4109827 , -1.14410441,  0.78461122,  0.68790168,
       -0.88954832,  0.46791561, -0.74599362, -0.01833718, -0.4210761 ])

In [32]:
martix = np.random.randn(3,4)

In [33]:
martix

array([[ 0.36477594,  0.18633181, -0.27718354,  2.06576463],
       [ 0.04953991, -0.54628807,  0.53723133,  0.34285252],
       [ 0.19212966, -0.30872349,  0.58510324,  0.24316552]])

In [34]:
matrix = np.random.randn(500)

In [35]:
matrix

array([ 1.70947310e-01,  2.55182403e-01, -5.80807202e-01,  1.31500866e+00,
        8.00158275e-01,  1.43617064e+00, -2.68862157e-01, -1.34444103e+00,
        2.07539757e-01,  1.71816703e+00, -1.04392088e+00, -1.22125962e+00,
       -7.26257965e-01, -1.55195978e-01, -2.95938223e-01, -4.96796462e-01,
       -1.55877731e+00,  1.23502641e+00,  1.02231376e-01,  3.95117681e-01,
        2.09975682e-01,  5.71658037e-01, -1.22427930e+00, -7.36608795e-01,
       -2.50863912e-01, -3.27453693e-01, -3.33945316e-01,  2.40554576e-02,
        4.37548610e-01,  1.03466177e+00,  8.36495260e-02,  7.47262847e-01,
       -8.65906553e-01,  1.01541665e+00, -6.03284118e-01,  3.21002033e-01,
        6.21371609e-01,  5.33091170e-01,  2.29297961e-02, -1.41549374e-01,
        9.86978790e-01, -4.02747241e-02, -1.21259325e+00, -6.61124393e-01,
       -4.41784019e-01,  7.28836801e-01,  2.42726015e-01,  1.17787715e+00,
       -5.96958026e-01,  4.23441773e-01,  1.69581612e+00,  3.10908083e-02,
        2.35130792e-01,  

In [36]:
np.mean(matrix)

0.05248644972037083

In [37]:
np.sum(matrix)

26.243224860185414

In [40]:
import pandas as pd

In [41]:
ser = pd.Series([1,2,3,4,5])

In [42]:
ser

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [43]:
type(ser)

pandas.core.series.Series

In [44]:
ser.dtype

dtype('int64')

In [45]:
ser.tolist()

[1, 2, 3, 4, 5]

In [46]:
type(ser)

pandas.core.series.Series

In [47]:
type(ser.tolist())

list