In [2]:
import numpy as np

In [3]:
arr = np.array([2, 80, 1, 97, 5])

In [4]:
# for finding the minimum out of all numbers in the array...
np.min(arr)

1

In [5]:
np.max(arr)

97

In [6]:
# for getting the position(index) of the minimum number in the array
np.argmin(arr)

2

In [7]:
# for getting the pos. of the maximum number in the array
np.argmax(arr)

3

In [8]:
# for finding the square root of all the numbers in the array...
np.sqrt(arr)

array([1.41421356, 8.94427191, 1.        , 9.8488578 , 2.23606798])

In [9]:
arr

array([ 2, 80,  1, 97,  5])

In [11]:
# exp of certain number implies e^(number) where e = 2.71828
np.exp(arr)

array([7.38905610e+00, 5.54062238e+34, 2.71828183e+00, 1.33833472e+42,
       1.48413159e+02])

In [12]:
2.71828 ** 2

7.3890461584

In [14]:
np.sin(arr)

array([ 0.90929743, -0.99388865,  0.84147098,  0.37960774, -0.95892427])

In [15]:
np.cos(arr)

array([-0.41614684, -0.11038724,  0.54030231, -0.92514754,  0.28366219])

In [17]:
# to get fixed number of numbers which are evenly spaced.
# np.linspace(interval_limit_begin, interval_limit_end, no._of_evenly_numbers_needed)  (=> its important function****)
np.linspace(1, 15, 50)

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [18]:
np.linspace(1, 50, 5)

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [21]:
arr2 = np.array([1, 2, 3, 0], dtype = 'bool')

In [22]:
arr2

array([ True,  True,  True, False])

In [23]:
arr2 = np.array([1, 0, 1, 1], dtype = 'bool')
arr2

array([ True, False,  True,  True])

In [24]:
for i in arr2:
    print(i)

True
False
True
True
